start: _NEWLINE? chapter (_NEWLINE? "---" "-"* _NEWLINE?  chapter)* _NEWLINE?
chapter: line (_NEWLINE line)*
line: (word|word_ruby|word_mora)+

word: WORD | "(" WORD+ ")"
word_ruby: word "[" RUBY_TEXT "]"
word_mora: (word|word_ruby) "." INTEGER

COMMENT: "#" /[^\n]/*
WORD: /[^#\n\[\]\(\)\.-]/
RUBY_TEXT: /[^\]]+/

INTEGER: /\d+/

// %import common.WS
// %import common.NEWLINE -> _NEWLINE
// %ignore WS
// %ignore _NEWLINE
_NEWLINE: /\n+/

%ignore /[\f\r\xa0]/
%ignore COMMENT
